# This compose file is used for local development only
# It is not used in production
services:
  postgresdb:
    image: postgres:16
    restart: 'no'
    environment:
      POSTGRES_USER: ${DKR_DB_USER}
      POSTGRES_PASSWORD: ${DKR_DB_PSWRD}
      POSTGRES_DB: ${DKR_DB_NAME}
    ports:
      - $DKR_DB_LOCAL_PORT:$DKR_DB_DOCKER_PORT
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5

  backend-next:
    build: .
    command: sh -c "yarn db:deploy && yarn dev"
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgresdb:
        condition: service_healthy
volumes:
  db-data:
